public static class SeedData
{
    public static IEnumerable<Player> CreateSamplePlayers()
    {
        return new List<Player>
        {
            new Player("Cristiano Ronaldo", "Portugal", 800, 37),
            new Player("Lionel Messi", "Argentina", 750, 35),
            new Player("Kylian Mbappe", "France", 200, 23),
            new Player("Neymar Jr", "Brazil", 350, 30),
            new Player("Robert Lewandowski", "Poland", 500, 33),
            new Player("Bruno Fernandes", "Portugal", 150, 27),
            new Player("Di Maria", "Argentina", 100, 34),
            new Player("Phil Foden", "England", 50, 21),
            new Player("Kevin De Bruyne", "Belgium", 70, 30),
            new Player("Eden Hazard", "Belgium", 120, 31),
            new Player("Diogo Costa", "Portugal", 0, 25),
            new Player("José Sá", "Portugal", 0, 32),
            new Player("Nuno Tavares", "Portugal", 1, 25),
            new Player("Tomás Araújo", "Portugal", 1, 22),
            new Player("António Silva", "Portugal", 0, 21),
            new Player("Diogo Dalot", "Portugal", 2, 25),
            new Player("Nélson Semedo", "Portugal", 0, 31),
            new Player("João Cancelo", "Portugal", 3, 30),
            new Player("Nuno Mendes", "Portugal", 5, 22),
            new Player("João Palhinha", "Portugal", 2, 29),
            new Player("Pedro Gonçalves", "Portugal", 160, 26),
            new Player("Bernardo Silva", "Portugal", 140, 30),
            new Player("João Neves", "Portugal", 50, 20),
            new Player("Otávio", "Portugal", 90, 29),
            new Player("Rúben Neves", "Portugal", 80, 27),
            new Player("Vitinha", "Portugal", 70, 24),
            new Player("Geovany Quenda", "Portugal", 20, 17),
            new Player("Francisco Trincão", "Portugal", 30, 25),
            new Player("João Félix", "Portugal", 40, 25),
            new Player("Fábio Silva", "Portugal", 25, 22),
            new Player("Rafael Leão", "Portugal", 60, 25),
            new Player("Pedro Neto", "Portugal", 35, 24),
            new Player("Diogo Jota", "Portugal", 45, 28),
            new Player("Francisco Conceição", "Portugal", 30, 22),
            new Player("Wálter Benítez", "Argentina", 0, 32),
            new Player("Emiliano Martínez", "Argentina", 0, 32),
            new Player("Gerónimo Rulli", "Argentina", 0, 32),
            new Player("Gonzalo Montiel", "Argentina", 50, 27),
            new Player("Facundo Medina", "Argentina", 40, 25),
            new Player("Leonardo Balerdi", "Argentina", 60, 26),
            new Player("Nicolás Tagliafico", "Argentina", 30, 32),
            new Player("Nahuel Molina", "Argentina", 20, 26),
            new Player("Cristian Romero", "Argentina", 25, 26),
            new Player("Lisandro Martínez", "Argentina", 35, 27),
            new Player("Alexis Mac Allister", "Argentina", 100, 26),
            new Player("Enzo Fernández", "Argentina", 110, 23),
            new Player("Rodrigo De Paul", "Argentina", 120, 30),
            new Player("Exequiel Palacios", "Argentina", 90, 26),
            new Player("Giovani Lo Celso", "Argentina", 80, 28),
            new Player("Thiago Almada", "Argentina", 70, 23),
            new Player("Leandro Paredes", "Argentina", 60, 30),
            new Player("Nico Paz", "Argentina", 50, 20),
            new Player("Facundo Buonanotte", "Argentina", 40, 20),
            new Player("Enzo Barrenechea", "Argentina", 55, 21),
            new Player("Alejandro Garnacho", "Argentina", 65, 20),
            new Player("Julián Álvarez", "Argentina", 70, 24),
            new Player("Lautaro Martínez", "Argentina", 100, 27),
            new Player("Valentín Castellanos", "Argentina", 40, 26),
            new Player("Ángel Di María", "Argentina", 110, 36),
            new Player("Paulo Dybala", "Argentina", 95, 31)
        };
    }
}